In [1]:
import tensorflow as tf
import numpy as np
np.random.seed(42)

In [5]:
class network():
    def __init__(self,
                input_states,
                num_layers,
                nurons_list,
                output_states,
                session):
        
        # Check if the number of neurons in each layer is 
        if len(nurons_list) != num_layers:
            raise ValueError("nurons_list != num of layers")
        
        # Initialize the network
        self.input_states = tf.placeholder(dtype=tf.float64, shape=[None, input_states])
        
        # Create a dictonary of weight and states based on the input layers
        # Compute the dimentions of the weight bias matrix
        temp_array = [input_states] + nurons_list.append(output_states)
        
        self.weights = {}
        self.bias = {}
        for i in range(0, len(temp_array)-1):
            self.weights["w"+str(i)] = tf.Variable(np.random.rand(temp_array[i], temp_array[i+1]), dtype=tf.float64)
            self.bias["b"+str(i)] = tf.Variable(np.random.rand(temp_array[i+1]), dtype=tf.float64)
            
        
        # Set the computation graph for the network 
        foward_pass = {} # Holds the nodes 
        for i in range(0, len(nurons_list)):
            forward_pass[] = self.input_states, self.weights["w"+str(i)] + self.bias["b"+str(i)]
        
        """
        # Loss function 
        self.loss = tf.reduce_mean(tf.square(self.z2 - self.y_t))
        # Optimizer
        self.optimizer = tf.train.AdamOptimizer()
        # Training
        self.train = self.optimizer.minimize(self.loss)
        # Set the tf.session
        self.sess = session;
        # Initialize the variables
        self.sess.run(tf.global_variables_initializer())
        """
    def set_weights(self, target):
        pass
    
    def load_weights(self, target):
        pass
        
    def predict_on_batch(self, input_x):
        pass
    
    def fit(self, x_train, y_train):
        self.sess.run(self.train, {self.state:x_train, self.y_t:y_train})

In [6]:
network(2,2,[2],3,tf.Session())

ValueError: nurons_list != num of layers

In [32]:
a = tf.Session()
test1 = network(2,3, a)
test2 = network(2,3, a)

In [33]:
a.run(test1.w1)

array([[ 0.90177403,  0.20347274,  0.06697361,  0.87735045,  0.38940494,
         0.54176096,  0.96806581,  0.06656473,  0.64831801,  0.07410542,
         0.37546893,  0.80381455,  0.43347223,  0.99718235,  0.55905928,
         0.32116215,  0.22011133,  0.35052053,  0.37253327,  0.06871368,
         0.3695742 ,  0.46423852,  0.72273775,  0.65672948,  0.70876566,
         0.00836368,  0.2176674 ,  0.66168429,  0.48398937,  0.00531348,
         0.80449464,  0.77280957,  0.54841916,  0.06646333,  0.76651505,
         0.58371359,  0.78195998,  0.75174699,  0.80300207,  0.51800807,
         0.14032452,  0.67115747,  0.62047379,  0.74225319,  0.16988101,
         0.1949752 ,  0.89040952,  0.7499778 ,  0.90822849,  0.75871532,
         0.59715531,  0.65413274,  0.88912792,  0.57880675,  0.63239132,
         0.15647672,  0.47392122,  0.71639711,  0.2709427 ,  0.20225418,
         0.31382681,  0.24150063,  0.21491264,  0.42485084],
       [ 0.90783851,  0.50705965,  0.18792038,  0.07697167,  0.

In [34]:
a.run(test2.w1)

array([[ 0.28104975,  0.17349605,  0.37975152,  0.80144578,  0.39209358,
         0.75076965,  0.1254863 ,  0.77277142,  0.23693332,  0.67739313,
         0.56578155,  0.92914472,  0.38732252,  0.06616519,  0.01915549,
         0.82685856,  0.52473564,  0.77524405,  0.2344256 ,  0.34508375,
         0.03010387,  0.96149232,  0.66786791,  0.93320509,  0.26549641,
         0.61146361,  0.67849997,  0.3175497 ,  0.84810924,  0.94716146,
         0.88485512,  0.73906698,  0.27746468,  0.28161604,  0.96336032,
         0.0102845 ,  0.71604997,  0.70624616,  0.62268954,  0.99010885,
         0.31187944,  0.33997186,  0.0789394 ,  0.44279814,  0.26104853,
         0.3433867 ,  0.83457179,  0.93548451,  0.18573307,  0.37250893,
         0.92863056,  0.06180846,  0.09236053,  0.16279099,  0.59521283,
         0.15047227,  0.96807638,  0.44671453,  0.50151796,  0.24665862,
         0.47096025,  0.66191363,  0.75117714,  0.75386808],
       [ 0.57789111,  0.90435977,  0.81740785,  0.75704811,  0.

In [35]:
test2.set_weights(test1)

In [36]:
a.run(test2.w1) - a.run(test1.w1)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [37]:
q = np.asarray([12, 34, 12, 43, 55, 123])
q = q.reshape(3,2)
test1.predict_on_batch(q)
p = test2.predict_on_batch(q)

In [38]:
test1.fit(q, p)